### ISSUE TITLE
PebbleKit doesn't include "full" Bitcode

### ISSUE THREAD

**Issue by sjmerel** [pebble/pebble-ios-sdk#12]
Please provide a build with bitcode enabled, so developers can enable bitcode in our apps.

**Comment by drodriguez** [comment]
We are now providing builds with Bitcode which you should be able to use in your Bitcode enabled apps. Which errors are you experiencing and why do you think they are related to Bitcode?

**Comment by sjmerel** [comment]
Hmm, I was building yesterday and it complained about not having bitcode in the Pebble framework until I disabled bitcode in my app.  Today I did a clean rebuild and the warning is gone; maybe a problem with Xcode keeping old object files around?  Sorry about that!

**Comment by sjmerel** [comment]
It turns out this happens only when I archive, not when I do an ordinary build... so I'm still seeing this problem.

Here's the error:
`ld: bitcode bundle could not be generated because '../../../ext/pebble/pebble-ios-sdk/PebbleKit.framework/PebbleKit(libPebbleKit.a-armv7-master.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

Are you building the framework with xcodebuild?  We do that for our frameworks, and we found we needed to explicitly add the "-fembed-bitcode" argument (see http://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled)

**Comment by drodriguez** [comment]
Yes, we know about `-fembed-bitcode` and `-fembed-bitcode-marker`, we think we found a solution but we might have been wrong. Testing if some binary has “real” bitcode is a little tricky (or our method doesn’t actually work).

We will try to find out a solution. Sorry for the inconvenience, for now you will have to submit without bitcode (if possible).

**Comment by mrcljx** [comment]
Hi @sjmerel, thanks for reporting it. :+1:
It should be fixed in _3.1.0_ which is available now.

**Comment by Genki-S** [comment]
Hi @sirlantis, thank you for dealing with this problem!

I tried PebbleKit 3.1.0 with Xcode 7.1.1, and still getting the same error with @sjmerel below when I try to archive (Build works fine):

`ld: bitcode bundle could not be generated because '/Users/genki/dev/PebbleStanfordStudySwift/Pods/PebbleKit/PebbleKit.framework/PebbleKit' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

Could you recheck it includes full bitcode? Thanks!

**Comment by mrcljx** [comment]
Thanks @Genki-S for checking up on this. Next patch release will contain full bitcode.

**Comment by Genki-S** [comment]
Thanks a lot @sirlantis! Could you tell me when the next patch release will be?

**Comment by mrcljx** [comment]
@Genki-S I just released 3.1.1 which should contain full Bitcode. At least the binary is now twice the size. Does it work for you?

**Comment by Genki-S** [comment]
@sirlantis It works! I confirmed I can archive my project using PebbleKit 3.1.1 with CocoaPods. Thank you so much for your lightning :zap: fast fix!
