### ISSUE TITLE
new pebblekit (3.0.0) produces lots of warnings in xcode 7

### ISSUE THREAD

**Issue by motocodeltd** [pebble/pebble-ios-sdk#5]
about 80 instances of
warning: (x86_64) /var/folders/1y/tt8clntj75q79krs_0qwh8tw0000gp/T/tmpv8GzMH/Build/Intermediates/PebbleKit.build/Release-iphonesimulator/PebbleKit.build/Objects-normal/x86_64/PBWatch+LinkStatus.o unable to open object file: No such file or directory

& friends.

**Comment by C-D-Lewis** [comment]
@sirlantis We found this when building the tutorials. Any additional info you can share?

**Comment by mrcljx** [comment]
@C-D-Lewis We haven't found a reliable way how to reproduce this yet.
@thenewrohirrim Are you using CocoaPods? Then it might be this issue: https://github.com/CocoaPods/CocoaPods/issues/4237

**Comment by mrcljx** [comment]
I've also seen this with other iOS frameworks:
- [reveal](http://support.revealapp.com/discussions/questions/55551-xcode-compile-errors)
- [parse](https://groups.google.com/forum/#!msg/parse-developers/TmFfywd-lZY/eJJYx83qBwAJ)

Culprit might be the _Build Active Architecture Only_ setting of the Pods project.

**Comment by mrcljx** [comment]
Workaround for now: Changing the debug information format from _DWARF with DSYM_ to _DWARF_.

**Comment by jeradesign** [comment]
I'm seeing this. No Pods here.

**Comment by sjmerel** [comment]
I think switching from "DWARF with DSYM" to "DWARF" will prevent you from getting stack traces from users.

**Comment by drodriguez** [comment]
The issue is probably related or similar to https://github.com/Carthage/Carthage/issues/924

The DWARF debug information included in the binary itself for frameworks seems to store absolute references to original build product directories for some reason. When we test the build products, the build results are probably still in those temporal directories and we don’t see those warnings. However when the framework is used in some other computer, those absolute paths are not longer valid, and you see those warnings. Having the `dSYM` file will not help either.

**Comment by mrcljx** [comment]
Hi everyone, this issue should be fixed with PebbleKit 3.1.0 which we just released. Thanks for reporting this. :+1:

**Comment by bradboose** [comment]
Hi @sirlantis - I'm actually still seeing this issue with Xcode 7.2 and the PebbleKit-Static 3.1.1 Framework.  Was this issue fixed in there as well?

**Comment by mrcljx** [comment]
@bradboose Sadly not. Xcode 7 issues these warnings for static libraries when dSYM is enabled. The 'solution' was to make PebbleKit a dynamic library.

**Comment by bradboose** [comment]
Gotcha - thanks for the info.

**Comment by appsandwich** [comment]
Would it be possible to provide a static version of the framework, compiled with the settings change? We have to use the static framework for legacy reasons, and having 200+ warnings isn't exactly ideal.

Thanks,

Vinny.

**Comment by drodriguez** [comment]
I haven’t tried, but checkout `man 1 strip`.

Correction: maybe the right command line is `strip -arch all -S -x -u -r PebbleKit-Static`

**Comment by appsandwich** [comment]
@drodriguez That worked perfectly - thank you!
